local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#121C2A", bg = "#FFF5E8"},
BufferCurrent = {bg = "#FFF5E8"},
BufferCurrentMod = {link = "BufferCurrent"},
BufferInactive = {fg = "#14181E", bg = "#FFF5E8"},
BufferInactiveMod = {link = "BufferInactive"},
BufferVisible = {link = "BufferInactive"},
Character = {fg = "#DE3A54"},
CmpItemKindClass = {fg = "#DE3A54"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#871E29"},
CmpItemKindEnum = {fg = "#C0AE4F"},
CmpItemKindEnumMember = {fg = "#C0AE4F"},
CmpItemKindEvent = {},
CmpItemKindField = {fg = "#5B807E"},
CmpItemKindFile = {fg = "#9F7038"},
CmpItemKindFolder = {fg = "#8C653A"},
CmpItemKindFunction = {fg = "#B150C9"},
CmpItemKindInterface = {fg = "#3C8581"},
CmpItemKindKeyword = {fg = "#234872"},
CmpItemKindMethod = {fg = "#1F4E4C"},
CmpItemKindModule = {fg = "#DE3A54"},
CmpItemKindOperator = {},
CmpItemKindProperty = {fg = "#608F8C"},
CmpItemKindReference = {},
CmpItemKindSnippet = {fg = "#5F8437"},
CmpItemKindStruct = {fg = "#DE3A54"},
CmpItemKindText = {fg = "#121C2A"},
CmpItemKindTypeParameter = {},
CmpItemKindUnit = {},
CmpItemKindValue = {},
CmpItemKindVariable = {fg = "#427DB9"},
Comment = {fg = "#6B6B5D"},
Constant = {fg = "#9F7038"},
CursorLine = {bg = "#FEE8C9"},
TelescopeSelection = {link = "CursorLine"},
Delimiter = {fg = "#C0AE4F"},
DiagnosticError = {fg = "#C22F3F"},
DiagnosticHint = {fg = "#427DB9"},
DiagnosticInfo = {fg = "#B150C9"},
DiagnosticWarn = {fg = "#9F7038"},
DiffAdd = {fg = "#5F8437"},
DiffChange = {fg = "#3C8581"},
DiffDelete = {fg = "#871E29"},
DiffText = {fg = "#70257C"},
Error = {fg = "#C22F3F"},
ErrorMsg = {fg = "#C22F3F", bold = true},
FloatBorder = {fg = "#427DB9", bg = "#FEE8C9"},
TelescopeBorder = {link = "FloatBorder"},
Function = {fg = "#234872"},
Identifier = {fg = "#427DB9"},
IncSearch = {bg = "#5D411D"},
LineNr = {fg = "#354A66"},
NormalFloat = {bg = "#FEE8C9"},
Number = {fg = "#B150C9"},
Operator = {fg = "#121C2A"},
PreProc = {fg = "#70257C", bold = true},
Search = {bg = "#9F7038"},
Statement = {fg = "#234872", bold = true},
String = {fg = "#5F8437"},
Substitute = {fg = "#DE3A54", bg = "#5D411D"},
TelescopeMatching = {fg = "#427DB9"},
TelescopeMultiSelection = {fg = "#427DB9", bg = "#FEE8C9"},
TelescopePromptPrefix = {fg = "#234872"},
Type = {fg = "#5B807E", italic = true},
Special = {link = "Type"},
["@diff.delta"] = {fg = "#3C8581"},
["@diff.minus"] = {fg = "#871E29"},
["@diff.plus"] = {fg = "#5F8437"},
["@markup.heading"] = {fg = "#121C2A", bold = true},
["@markup.heading.1"] = {fg = "#234872", bold = true},
["@markup.heading.2"] = {fg = "#427DB9", bold = true},
["@markup.heading.3"] = {fg = "#3C8581", bold = true},
["@markup.heading.4"] = {fg = "#B150C9", bold = true},
["@markup.italic"] = {fg = "#427DB9", italic = true},
["@markup.link"] = {fg = "#3C8581"},
["@markup.list"] = {fg = "#121C2A"},
["@markup.list.checked"] = {fg = "#5F8437"},
["@markup.list.unchecked"] = {fg = "#871E29"},
["@markup.math"] = {fg = "#5B807E"},
["@markup.quote"] = {fg = "#427DB9", italic = true},
["@markup.raw"] = {fg = "#5B807E"},
["@markup.strikethrough"] = {fg = "#871E29", strikethrough = true},
["@markup.strong"] = {fg = "#234872", bold = true},
["@markup.underline"] = {fg = "#9F7038"},
["@string"] = {fg = "#5F8437"},
["@string.escape"] = {fg = "#C0AE4F"},
["@variable"] = {fg = "#427DB9"},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd [[
	highlight clear
	set t_Co=256
	set background=light
	let g:colors_name='uniwa-paper'
]]

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
