local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#121C2A", bg = "#BED6FA"},
Pmenu = {link = "Normal"},
TabLine = {link = "Normal"},
BufferCurrent = {bg = "#C7DCFA"},
BufferCurrentMod = {link = "BufferCurrent"},
BufferInactive = {fg = "#14181E", bg = "#BED6FA"},
BufferInactiveMod = {link = "BufferInactive"},
BufferVisible = {link = "BufferInactive"},
Character = {fg = "#F05F75"},
CmpItemKindClass = {fg = "#F05F75"},
CmpItemKindColor = {},
CmpItemKindConstant = {fg = "#9F1E2E"},
CmpItemKindEnum = {fg = "#D1BC4B"},
CmpItemKindEnumMember = {fg = "#D1BC4B"},
CmpItemKindEvent = {},
CmpItemKindField = {fg = "#6A9996"},
CmpItemKindFile = {fg = "#C0843C"},
CmpItemKindFolder = {fg = "#A87740"},
CmpItemKindFunction = {fg = "#C86AE2"},
CmpItemKindInterface = {fg = "#409F9A"},
CmpItemKindKeyword = {fg = "#245487"},
CmpItemKindMethod = {fg = "#1F5B59"},
CmpItemKindModule = {fg = "#F05F75"},
CmpItemKindOperator = {},
CmpItemKindProperty = {fg = "#6DA5A2"},
CmpItemKindReference = {},
CmpItemKindSnippet = {fg = "#729D3B"},
CmpItemKindStruct = {fg = "#F05F75"},
CmpItemKindText = {fg = "#121C2A"},
CmpItemKindTypeParameter = {},
CmpItemKindUnit = {},
CmpItemKindValue = {},
CmpItemKindVariable = {fg = "#4795DD"},
Comment = {fg = "#6B6B5D"},
Constant = {fg = "#C0843C"},
CursorLine = {bg = "#ACCCF7"},
PmenuSel = {link = "CursorLine"},
TelescopeSelection = {link = "CursorLine"},
Delimiter = {fg = "#D1BC4B"},
DiagnosticError = {fg = "#D82C41"},
DiagnosticHint = {fg = "#4795DD"},
DiagnosticInfo = {fg = "#C86AE2"},
DiagnosticWarn = {fg = "#C0843C"},
DiffAdd = {fg = "#729D3B"},
DiffChange = {fg = "#409F9A"},
DiffDelete = {fg = "#9F1E2E"},
DiffText = {fg = "#852694"},
Error = {fg = "#D82C41"},
ErrorMsg = {fg = "#D82C41", bold = true},
FloatBorder = {fg = "#4795DD", bg = "#ACCCF7"},
TelescopeBorder = {link = "FloatBorder"},
Function = {fg = "#245487"},
Identifier = {fg = "#4795DD"},
IncSearch = {bg = "#6D4C1C"},
LineNr = {fg = "#3C5776"},
NormalFloat = {bg = "#ACCCF7"},
Number = {fg = "#C86AE2"},
Operator = {fg = "#121C2A"},
PreProc = {fg = "#852694", bold = true},
Search = {bg = "#C0843C"},
Statement = {fg = "#245487", bold = true},
String = {fg = "#729D3B"},
Substitute = {fg = "#F05F75", bg = "#6D4C1C"},
TabLineFill = {bg = "#BED6FA"},
TabLineSel = {fg = "#BED6FA", bg = "#4795DD"},
TelescopeMatching = {fg = "#4795DD"},
TelescopeMultiSelection = {fg = "#4795DD", bg = "#ACCCF7"},
TelescopePromptPrefix = {fg = "#245487"},
Type = {fg = "#6A9996", italic = true},
Special = {link = "Type"},
["@diff.delta"] = {fg = "#409F9A"},
["@diff.minus"] = {fg = "#9F1E2E"},
["@diff.plus"] = {fg = "#729D3B"},
["@markup.heading"] = {fg = "#121C2A", bold = true},
["@markup.heading.1"] = {fg = "#245487", bold = true},
["@markup.heading.2"] = {fg = "#4795DD", bold = true},
["@markup.heading.3"] = {fg = "#409F9A", bold = true},
["@markup.heading.4"] = {fg = "#C86AE2", bold = true},
["@markup.italic"] = {fg = "#4795DD", italic = true},
["@markup.link"] = {fg = "#409F9A"},
["@markup.list"] = {fg = "#121C2A"},
["@markup.list.checked"] = {fg = "#729D3B"},
["@markup.list.unchecked"] = {fg = "#9F1E2E"},
["@markup.math"] = {fg = "#6A9996"},
["@markup.quote"] = {fg = "#4795DD", italic = true},
["@markup.raw"] = {fg = "#6A9996"},
["@markup.strikethrough"] = {fg = "#9F1E2E", strikethrough = true},
["@markup.strong"] = {fg = "#245487", bold = true},
["@markup.underline"] = {fg = "#C0843C"},
["@string"] = {fg = "#729D3B"},
["@string.escape"] = {fg = "#D1BC4B"},
["@variable"] = {fg = "#4795DD"},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd [[
	highlight clear
	set t_Co=256
	set background=light
	let g:colors_name='uniwa-light'
]]

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
